version: '3.8'

services:
  
  web:
    image: your-app-image:latest
    build:
      context: .
    ports:
      - "5000:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=db;Database=YourDatabase;User=sa;Password=YourPassword
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network


  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Test1234
      - ACCEPT_EULA=Y
    networks:
      - app-network

  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
